name: Deploy Web Folder to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers when you push to main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web # This tells it to only deploy the web folder
          branch: gh-pages # The branch the website files will be pushed to
          cname: mov.<your_domain>.in # Added this line to preserve the subdomain on every push
